<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheelchair">
	<!-- Color are defined in materials.urdf.xacro -->

	<xacro:property name="M_PI" value="3.1415926535897931" />

	<xacro:property name="base_size_x"   value="0.63" />
	<xacro:property name="base_size_y"   value="0.31" />
	<xacro:property name="base_size_z"   value="0.30" />
	<xacro:property name="base_origin_x" value="0.0" />
	<xacro:property name="base_origin_y" value="0.0" />
	<xacro:property name="base_origin_z" value="0.0" />
	<xacro:property name="base_offset_z" value="0.078" />
	
	<xacro:property name="wheel_main_radius"      value="0.175" />
	<xacro:property name="wheel_main_width"       value="0.08" />
	<xacro:property name="wheel_main_offset_x"    value="0.095" />
	<xacro:property name="wheel_main_offset_y"    value="-0.295" />
	<xacro:property name="wheel_main_offset_z"    value="${wheel_main_radius-base_offset_z-base_size_z/2}" />
	<xacro:property name="wheel_secondary_radius" value="0.09" />
	<xacro:property name="wheel_secondary_width"  value="0.04" />
	<xacro:property name="wheel_front_offset_x"   value="0.385" />
	<xacro:property name="wheel_front_offset_y"   value="-0.285" />
	<xacro:property name="wheel_front_offset_z"   value="${wheel_secondary_radius-base_offset_z-base_size_z/2}" />
	<xacro:property name="wheel_back_offset_x"    value="-0.405" />
	<xacro:property name="wheel_back_offset_y"    value="-0.225" />
	<xacro:property name="wheel_back_offset_z"    value="${wheel_secondary_radius-base_offset_z-base_size_z/2}" />


<!-- ****************** Wheel macro ************************** -->
	<xacro:macro name="wheel" params="name parent *shape *location">
		<joint name="${name}_joint" type="continuous">
			<axis rpy="0 0 0" xyz="0 1 0"/>
			<parent link="${parent}_link"/>
			<child link="${name}_link"/>
			<xacro:insert_block name="location"/>
    	</joint>
		<link name="${name}_link">
			<inertial>
				<mass value="5"/>
				<inertia
					ixx="1" ixy="0.0" ixz="0.0"
					iyy="1" iyz="0.0"
					izz="1"/>
			</inertial>
			<visual>
				<origin xyz="0 0 0" rpy="0 ${M_PI/2} ${M_PI/2}" />
				<geometry>
					<xacro:insert_block name="shape"/>
				</geometry>
				<material name="grey"/>
			</visual>

			<collision>
				<origin xyz="0 0 0" rpy="0 ${M_PI/2} ${M_PI/2}" />
				<geometry>
					<xacro:insert_block name="shape"/>
				</geometry>
			</collision>
		</link>
	</xacro:macro>

<!-- ******************  Base ************************** -->
	<!-- Wheelchair Base - Link -->
	<link name="base_link">
		<inertial>
			<mass value="100"/>
			<inertia
				ixx="1" ixy="0.0" ixz="0.0"
				iyy="1" iyz="0.0"
				izz="1"/>
		</inertial>
		<visual>
			<origin xyz="${base_origin_x} ${base_origin_y} ${base_origin_z}" rpy="0 0 0"/>
			<geometry>
				<box size="${base_size_x} ${base_size_y} ${base_size_z}"/>
			</geometry>
			<material name="black"/>
		</visual>

		<collision>
			<origin xyz="${base_origin_x} ${base_origin_y} ${base_origin_z}" rpy="0 0 0"/>
			<geometry>
				<box size="${base_size_x} ${base_size_y} ${base_size_z}"/>
			</geometry>
		</collision>
	</link>

<!-- ****************** Wheels ************************** -->
	<!-- Wheelchair Wheel0 - Link -->
	<xacro:wheel name="wheel0" parent="base">
		<cylinder radius="${wheel_main_radius}" length="${wheel_main_width}"/>
		<origin xyz="${wheel_main_offset_x} ${wheel_main_offset_y} ${wheel_main_offset_z}" rpy="0 0 0"/>
	</xacro:wheel>

	<!-- Wheelchair Wheel1 - Link -->
	<xacro:wheel name="wheel1" parent="base">
		<cylinder radius="${wheel_main_radius}" length="${wheel_main_width}"/>
		<origin xyz="${wheel_main_offset_x} ${-wheel_main_offset_y} ${wheel_main_offset_z}" rpy="0 0 0"/>
	</xacro:wheel>

	<!-- Wheelchair BackWheel0 - Link -->
	<xacro:wheel name="backwheel0" parent="base">
		<cylinder radius="${wheel_secondary_radius}" length="${wheel_secondary_width}"/>
		<origin xyz="${wheel_back_offset_x} ${wheel_back_offset_y} ${wheel_back_offset_z}" rpy="0 0 0"/>
	</xacro:wheel>

	<!-- Wheelchair BackWheel1 - Link -->
	<xacro:wheel name="backwheel1" parent="base">
		<cylinder radius="${wheel_secondary_radius}" length="${wheel_secondary_width}"/>
		<origin xyz="${wheel_back_offset_x} ${-wheel_back_offset_y} ${wheel_back_offset_z}" rpy="0 0 0"/>
	</xacro:wheel>
	
	<!-- Wheelchair FrontWheel0 - Link -->
	<xacro:wheel name="frontwheel0" parent="base">
		<cylinder radius="${wheel_secondary_radius}" length="${wheel_secondary_width}"/>
		<origin xyz="${wheel_front_offset_x} ${wheel_front_offset_y} ${wheel_front_offset_z}" rpy="0 0 0"/>
	</xacro:wheel>
	
	<!-- Wheelchair FrontWheel1 - Link -->
	<xacro:wheel name="frontwheel1" parent="base">
		<cylinder radius="${wheel_secondary_radius}" length="${wheel_secondary_width}"/>
		<origin xyz="${wheel_front_offset_x} ${-wheel_front_offset_y} ${wheel_front_offset_z}" rpy="0 0 0"/>
	</xacro:wheel>

</robot>
